//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editor
    {
        public int editor_id { get; set; }
        public string editor_fullname { get; set; }
        public Nullable<bool> editor_sex { get; set; }
        public string editor_fb { get; set; }
        public string editor_phone { get; set; }
        public string editor_time { get; set; }
        public string editor_intro { get; set; }
        public string editor_interests { get; set; }
        public string editor_enthusiasm { get; set; }
        public Nullable<int> user_id { get; set; }
        public string editor_zalo { get; set; }
        public Nullable<bool> editor_active { get; set; }
        public Nullable<int> editor_status { get; set; }
    
        public virtual User User { get; set; }
    }
}
